### ISSUE TITLE
Strings not being replaced

### ISSUE THREAD

**Issue by ktechmidas** [LedgerHQ/ledger-live-desktop#1195] opened 2018-07-18 16:03 UTC
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.0.3**
- Platform and version: **Windows 10**

#### Expected behavior

There should be a message when I've successfully sent funds.

#### Actual behavior

It appears the message has not been added to the strings in 1.0.3?

![image](https://user-images.githubusercontent.com/9920871/42893472-fe63f1aa-8ae6-11e8-9ae2-745643ea81e9.png)

#### Steps to reproduce the behavior

Send funds from BTC wallet, go all the way to the end where it should give you a success message.

**Comment by gre** [comment] 2018-07-18 16:08
I can't reproduce on 1.0.3, are you using the production app (the one released in releases) not development?
can you also make sure you have `Language: English` in settings?

**Comment by gre** [comment] 2018-07-18 16:09
if Use system language is used, can you tell us what is your system language?

thanks

**Comment by ktechmidas** [comment] 2018-07-18 16:38
Hi, yeah I'm using production and it's using the system language. I downloaded Windows 10 from Microsoft a long time ago in English. 

(However I'm residing in China right now... not entirely sure which English it would have given me, US/UK/etc - is there a way to check?)

Also, thanks a lot for fixing the other bug I raised the other day, didn't get a chance to thank you 👍

**Comment by ktechmidas** [comment] 2018-07-18 16:47
Alright, even if I override it and set it to "English (United Kingdom)" or "English (United States)" it still comes up with send.steps.confirmation.success.title

Strange issue... not entirely sure where the problem is.

**Comment by gre** [comment] 2018-07-18 16:48
yeah, normally Use system language, will just fallback on `en` if the system language is not in the list.

so this issue is very strange for us because we can't reproduce using 1.0.3. we'll have to try on Windows too.
what's very weird to me is that everything works except this 🤔

**Comment by NastiaS** [comment] 2018-07-19 08:53
Hi @ktechmidas , we were able to reproduce it on our side. it is unique to Windows. Thanks for reporting. We identified the problem and it will be fixed in the next patch/release.

**Comment by gre** [comment] 2018-07-19 13:01
this will be fixed in next 1.0.4

**Closed by gre** 2018-07-19 13:01 UTC

**Comment by ktechmidas** [comment] 2018-07-19 14:45
Thanks a lot @gre :+1:
