### ISSUE TITLE
ETH balance chart missing data first few days of each month

### ISSUE THREAD

**Issue by chadhamre** [LedgerHQ/ledger-live-desktop#3106] opened 2020-08-03 23:55 UTC
#### Ledger Live Version and Operating System

- tested on **Ledger Live 2.9.0**
- Platform and version: **Mac 10.15.6**

#### Expected behavior

Ledger Live should have correct balance for each day.

#### Actual behavior

Ledger Live is missing balances for the first few days of each month.

#### Steps to reproduce the behavior

<img width="864" alt="Screen Shot 2020-08-03 at 4 49 44 PM" src="https://user-images.githubusercontent.com/1864797/89238188-157ea780-d5aa-11ea-87bf-49b273559c9b.png">

**Comment by xyse** [comment] 2020-08-04 12:18
Had the same problem since a few Versions. For all currencies regardless of exchange selected for data gathering. 
![image](https://user-images.githubusercontent.com/12869664/89292917-60a5c280-d65d-11ea-91ea-e2345bfebef9.png)

**Comment by cthepot-ledger** [comment] 2020-09-18 08:41
Duplicate of #3122

**Closed by cthepot-ledger** 2020-09-18 08:41 UTC
Labels: bug

**Comment by bruno-t-de-renzo** [comment] 2020-10-23 08:35
Same here, though for first days of October the same behaviour doesn't happen, only for previous months
Ledger Live for Mac 2.14.0
