### ISSUE TITLE
[Linux] Ledger Live 2.0.0 and 2.0.1 fails to start / synchronize / access device

### ISSUE THREAD

**Issue by nix4me** [LedgerHQ/ledger-live-desktop#2685] opened 2020-03-05 23:18 UTC
Issues after v2.0.0 upgrade, and also in v2.0.1 in linux (slackware) same as [with](https://github.com/LedgerHQ/ledger-live-desktop/issues/2670) an added Fontconfig error that nobody else seems to have. After updating to v2,0,0 and closing ledger live it would not startup again until I renamed ~/.config/Ledger Live/ and letting it create a new Ledger Live directory but failed to connect to my nano s. The Fonconfig error was:

$./ledger-live-desktop-2.0.0-linux-x86_64.AppImage
Fontconfig warning: "/etc/fonts/fonts.conf", line 102: unknown element "blank"
Fontconfig warning: "/etc/fonts/conf.avail/66-wqy-zenhei-sharp-no13px.conf", line 11: Having multiple values in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/66-wqy-zenhei-sharp.conf", line 10: Having multiple values in isn't supported and may not work as expected
Ledger Live 2.0.0

So because I updated to v2.0.0 through the app I couldn't use the original ~/.config/Ledger Live
so I went back to v1.20.0 and let it create the Ledger Live dir. and installed all the apps and it works fine again.

Trying v2.0.1 it also fails unless I start without the ~/.config/Ledger Live directory spewing the same Fontconfig error as above.

**Comment by MortalKastor** [comment] 2020-03-06 16:18
We are aware of a Linux specific bug happening to some users only, where the app only prints `Ledger Live v2.0.1` in the shell and quit, which is fixed by removing `~/.config/Ledger Live, at the loss of all user data.

We are investing this exact issue, as the crashes introduced in v2 are our top priority right now.

Regarding the Fontconfig errors, it's most probably unrelated. Electron (the underlying framework of Ledger Live) rely on Fontconfig to get the available fonts, here it's just Fontconfig complaining about non-blocking issues with your system font configs, hence just "warning" and not "error".

Can you try running Ledger Live 2.0.1 without removing the whole `~/.config/Ledger Live` folder, but only delete the `SingletonCookie` and `SingletonLock` symlinks from the folder?

**Comment by nix4me** [comment] 2020-03-06 16:39
those symlinks disappear as soon as I shutdown ledger live

**Comment by gre** [comment] 2020-03-06 17:04
could you try a "bruteforce" approach consisting of deleting one by one a file in .`config/Ledger Live`, and reopen live to see if it fixes it and to see which file is causing the issue?

Just don't delete app.json and you should be fine in term of restoring the accounts.

essentially we need to find which file is creating the problem. (we migrated from Electron 2 to Electron 8 and it is very likely there is a glitch on one file)

**Comment by nix4me** [comment] 2020-03-06 17:20
Alright now I'm really confused but happy. I closed v1.20.1 down, left the
folder as is and tried to start v2.0.1 and it started up just fine.
I'm glad now I know app.json contains my accounts. Thanks for your help.

**Closed** 2020-03-06 17:27 UTC

**Comment by MortalKastor** [comment] 2020-03-07 14:57
> those symlinks disappear as soon as I shutdown ledger live

This is the intended behavior, the symlinks are used by Electron apps to prevent starting a second time if it's already running, and for some people, after the update the symlinks stay while no Ledger Live is running and prevents starting the app.

But those links reference a specific PID, and should only be valid if said PID is running.

My guess here, is that during the upgrade, a zombie thread from the old version of Ledger Live keeps on running, creating the issue.

> Alright now I'm really confused but happy. I closed v1.20.1 down, left the
folder as is and tried to start v2.0.1 and it started up just fine.

Did you, by any chance, reboot, or log-out from your computer between the time you experienced the broken behavior, and the time it went on working fine?

**Comment by nix4me** [comment] 2020-03-07 16:48
no this machine runs 24/7 and usually does for months. I think those
symlinks are what caused this issue. I was going back and forth a few times
with allowing LL to make a new directory
and trying the original directory that I had backed up. Both 2.0.0 and
2.0.1 would only start with the new one they'd create. So if those symlinks
were in the original directory with a thread still running
that would explain this behavior?
I have a conky display on my desktop that shows the top 3 processor, and
top 3 ram hogs presently that I usually look at when I restart an app but
it wouldn't necessarily
be listed there anyway.
