### ISSUE TITLE
Bitcoin: be able to choose unspent outputs

### ISSUE THREAD

**Issue by bfilipek** [LedgerHQ/ledger-live-desktop#1696] opened 2018-12-08 09:58 UTC
When user send Bitcoin, unspend outputs are merged and send to one wallet.

**For example:** 
Unspent outputs:
A: 0,5 BTC
B: 0,5 BTC
C: 0,5 BTC

When user send 0,1 BTC, rest of unspent outputs will be merged  and send to new the wallet.
So finally our wallet will be looks like:
D: 1,4 BTC

In this point user shows how many BTC have. Sometime it is not desirable (for security reasons).

**Comment by cthepot-ledger** [comment] 2020-09-14 08:44
Duplicate of #1234

**Closed by cthepot-ledger** 2020-09-14 08:44 UTC
Labels: feature request
