### ISSUE TITLE
No reply from aeternity

### ISSUE THREAD

**Issue by Shiningheaven** [LedgerHQ/ledger-live-desktop#3171] opened 2020-09-09 20:13 UTC
Hello,

Has the ledger update added?

We haven't heard from the developers, they have replied to us and sent us a version of the app which, after review, wasn't working properly.

If you know any developers within the Aeternity community don't hesitate to ask them to reach out to us.

Regards,
Clément

Ledger Support

#### Ledger Live Version

- Ledger Live **version_here**

**Comment by Shiningheaven** [comment] 2020-09-09 20:14
Ledger still don't have the right version to update 
Please coordinate with them to update it

**Comment by cthepot-ledger** [comment] 2020-09-18 08:47
Duplicate of #3131

**Closed by cthepot-ledger** 2020-09-18 08:47 UTC
