### ISSUE TITLE
No desktop icon on macOS

### ISSUE THREAD

**Issue by redmice** [LedgerHQ/ledger-live-desktop#4454] opened 2021-11-22 14:51 UTC
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.35.1
- Platform and version: MacOS 10.15.7

#### Expected behavior

The app should have an icon

#### Actual behavior

The app does not show an icon, but the default MacOS icon template

#### Steps to reproduce the behavior

Just install the app. It seems to be related to previously reported issues 

![Screen Shot 2021-11-22 at 11 49 34 PM](https://user-images.githubusercontent.com/6632376/142882205-03a6cc27-e9a1-49fb-b541-b8741ba3b678.png)

**Comment by spinlud** [comment] 2021-11-23 18:15
Same, just installed. 

`MacOS 10.15.7`

**Comment by phantomcrypt** [comment] 2021-11-24 19:08
The reason the icon is not showing is because the app icon got replaced by a new one after the update, but the dock doesn't recognise it automatically. Remove the icon from the dock, go to the applications list and drag the new icon. It should fix your problem.

**Comment by redmice** [comment] 2021-11-25 14:12
No, the problem is there from the beginning. Even with a fresh install for the first time, see the attached picture from the install. 

The icon is inside the Resources folder of the app, and the name is correct in the plist file, and can be open with preview, however, it doesn't show in Finder, LaunchPad or dock.

![Screen Shot 2021-11-25 at 11 06 50 PM](https://user-images.githubusercontent.com/6632376/143456250-1b370f03-8019-46e1-ba38-7f40a9b82260.png)

**Comment by phantomcrypt** [comment] 2021-11-25 16:06
Have you confirmed you are downloading from the [official ledger website](https://www.ledger.com/ledger-live/download), and if the [hash matches](https://www.ledger.com/ledger-live/lld-signatures) the DMG? it is important to exclude the chance that it is altered/corrupted.

**Comment by spinlud** [comment] 2021-11-25 16:08
Yes verified the checksum. Fresh install. No icon ¯\_(ツ)_/¯

**Comment by phantomcrypt** [comment] 2021-11-25 16:18
Try restarting the dock `$ killall Dock`

**Comment by FlyingHen** [comment] 2021-11-27 15:46
Started with version 2.35 update. Mac OS 10.14 too.

**Comment by FlyingHen** [comment] 2021-11-27 15:53
> The reason the icon is not showing is because the app icon got replaced by a new one after the update, but the dock doesn't recognise it automatically. Remove the icon from the dock, go to the applications list and drag the new icon. It should fix your problem.

Did that, and reinstalled Ledger from site. The issue is not in dock but at download, even after fresh reinstall from Ledger site. Generic Apple app icon appears at install window, applications folder, etc.

**Comment by phantomcrypt** [comment] 2021-11-27 19:59
Providing it is not the integrity of the DMG, I can only see some kind of icon cache issue.

Try this (taken [from](https://gist.github.com/ismyrnow/e92c6010cda9325b2d8811387a05f224)):
`$ sudo rm -rfv /Library/Caches/com.apple.iconservices.store; sudo find /private/var/folders \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \; ; sleep 3; sudo touch /Applications/* ; killall Dock; killall Finder`

If this doesn’t work it could be because `public.app-category.wallet` doesn’t exist as a category type in the [Apple docs](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/TP40009250-SW8). At least according to [electron-builder docs](https://www.electron.build/configuration/mac). But not sure if this would affect the icon.

However on 11.6.1 I do not experience any of these issues ¯\_(ツ)_/¯

**Comment by lk-geimfari** [comment] 2021-12-01 13:48
Having same issue on macOS Catalina (Version 10.15.7). 

Hardware: MacBook Pro (13-inch, 2017)

**Comment by Rem-ux** [comment] 2021-12-02 01:39
Experiencing same issue on macOS Mojave (Version 10.14.6).
Hardware: MacBook Pro (13-inch, Mid 2012)

**Comment by UFOGoldorak** [comment] 2021-12-11 18:36
Same issue on 2019 16" MBPro Mac OS 10.15.7.

**Comment by semeano** [comment] 2021-12-15 23:18
This has been fixed on [v2.36.2](https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.36.2)

**Comment by lk-geimfari** [comment] 2021-12-16 06:06
> This has been fixed on [v2.36.2](https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.36.2)

It works fine now. At least on my machine. Thank you!

**Comment by redmice** [comment] 2021-12-16 06:23
Yes, I can confirm it works for me too. Thank you!

**Comment by Rem-ux** [comment] 2021-12-16 17:30
Glad to confirm v2.36.2 resolved issue on macOS Mojave (Version 10.14.6). Thanks
Hardware: MacBook Pro (13-inch, Mid 2012)

**Closed** 2021-12-21 16:45 UTC

**Comment by demian85** [comment] 2022-04-06 13:15
Same issue happening to me right now after the last update!

**Comment by abdielnunes** [comment] 2022-04-06 21:01
With version 2.40.2 still with the same problem.

![Captura de Tela 2022-04-06 às 17 59 46](https://user-images.githubusercontent.com/2124666/162070123-18d65a86-f496-4c2c-9027-118089651d5c.png)
