### ISSUE TITLE
Push/Mail Notifications when funds were received

### ISSUE THREAD

**Issue by Flydancer** [LedgerHQ/ledger-live-desktop#2996] opened 2020-06-13 00:00 UTC
Add a feature to enable Push/Mail Notifications whenever one of my addresses has received funds.
Also a setting for enabling/disabled this feature per address or account would be great

**Comment by gre** [comment] 2020-06-13 06:34
We have been considering this kind of feature but this is very complex to implement and also complex to keep a good privacy (We do not know your accounts and your mail address on the backend)
Not sure exactly what you have in mind to do this. But maybe there are existing services that listen to a specific address you set and notify you.

**Comment by TrackRunny** [comment] 2020-06-17 01:13
This idea is cool, maybe even just a push notification on the desktop application would be good also?

**Comment by cthepot-ledger** [comment] 2020-09-16 17:01
Duplicate of #2584

**Closed by cthepot-ledger** 2020-09-16 17:01 UTC
