### ISSUE TITLE
Ripple ledger trustlines blocking sync

### ISSUE THREAD

**Issue by wehard** [LedgerHQ/ledger-live-desktop#1007] opened 2018-07-10 09:46 UTC
#### Ledger Live Version and Operating System

- Ledger Live 1.0.1
- Platform: Windows

#### Expected behavior

Should be able to add XRP account.

#### Actual behavior
Cannot add XRP account.
Sync failed, logs state ALV trust line is the problem.

From log: 

`{"level":"warn","message":"RippleJS: attempt to parse unknown currency 
 ALV","pname":"renderer","timestamp":"2018-07-10T09:31:20.456Z"}`

#### Steps to reproduce the behavior

XRP account needs to have open trust lines.
Then try to add account in Ledger Live.

**Comment by gre** [comment] 2018-07-10 10:07
We don’t support trustline at the moment

**Comment by wehard** [comment] 2018-07-10 10:07
OK but maybe just ignore other assets than XRP

**Comment by gre** [comment] 2018-07-10 11:18
@wehard do you know a quick way for me to reproduce it? thanks

**Comment by wehard** [comment] 2018-07-10 11:32
@gre I don't know if there is a quick way. ALV is an asset issued on the Ripple ledger by Allvor. Similar to ERC20 tokens on Ethereum. Right now it's not worth much. 

This is what you need to do to open a trust line for ALV:

[https://www.xrpchat.com/topic/21965-allvor-giving-free-alv-to-xrp-holders-whose-ripple-accounts-were-active-before-032818-5000-alv-13-alv-for-each-1-xrp-you-held-up-until-328-so-awesome/](url)

So basically you need to do that for a Ledger wallet XRP address, then claim the tokens from Allvor, and finally try to add the XRP wallet to Ledger Live.

I'm not 100% sure this is the problem, but it seems like it is, as the Ledger Live logs print out: `{"level":"warn","message":"RippleJS: attempt to parse unknown currency ALV","pname":"renderer","timestamp":"2018-07-10T09:31:20.456Z"}`

![capture](https://user-images.githubusercontent.com/4597568/42507453-e9a035ac-844d-11e8-9e68-892135b9e135.PNG)

**Comment by gre** [comment] 2018-07-10 11:57
i'm pretty sure this is the problem. (also i'm not elligible to this giveway apparently so i'll need to figure out another way)

**Comment by wehard** [comment] 2018-07-10 12:33
@gre You could issue your own asset on the ledger, but that might be too much of a hassle.

[https://bitcoin.stackexchange.com/questions/50759/is-it-still-possible-to-issue-your-own-assets-on-ripple](https://bitcoin.stackexchange.com/questions/50759/is-it-still-possible-to-issue-your-own-assets-on-ripple)

**Comment by jmos1277** [comment] 2018-07-11 17:54
I have the same issue and the same warning in my log file due to the unknown currency ALV.  If you would like to reproduce the warning, you can 
  (1) easily issue your own "unknown" currency on the XRP ledger using the Toast wallet; 
  (2) manually add a trustline to your Ledger XRP wallet for your newly minted currency; 
  (3) optionally, send some of the newly minted currency to your Ledger XRP wallet.
Here is a 10 minute YouTube video that provides a walkthrough of issuing a new currency on the XRP ledger: [https://www.youtube.com/watch?v=4TeLJp9eBlg](https://www.youtube.com/watch?v=4TeLJp9eBlg)

**Comment by gre** [comment] 2018-07-11 18:56
@jmos1277 do you think it's technically possible that someone directly send me some currency (like ALV) on one of my XRP address generated with the Ledger? I guess it's not without opening a trustline if i understand correctly?

**Comment by gre** [comment] 2018-07-11 19:02
I did buy a few ALV on GateHub and was thinking i could just send it to my address but I don't think it works like this 🤔

**Comment by wehard** [comment] 2018-07-11 19:18
I think you can open the trustline to Allvor address even though you're not eligible for the airdrop and then send this ALV from gatehub to yourself. I could also send you some but I'm out of town and I haven't got my Nano S with me. It might be that you don't even have to have a balance over zero to reproduce the error. Just having the open trustline might be enough.

**Comment by jmos1277** [comment] 2018-07-11 20:02
@gre Before you can send any ALV to your Ledger, you first need to set up a trustline on your Ledger XRP address.  Since you've already purchased some ALV, there is no need to create your own test currency.  I used the following tool to create a trustline using my mnemonic:
[https://github.com/WietseWind/xrp-trustline-set-commandline](https://github.com/WietseWind/xrp-trustline-set-commandline)
There is both an online and an offline version.  Using the online mnemonic version is probably easiest for testing purposed.

Allvor provides instructions and the required counterparty address for the trustline here:
[https://allvor.org/add-a-trust-line/](https://allvor.org/add-a-trust-line/)

I assume you've already created the trustline on your Gatehub wallet.

You can verify that you have successfully created the trustline using the Account Explorer at [xrpcharts.ripple.com](xrpcharts.ripple.com).  If you were successful, you should see an ALV balance of 0 in your wallet.

Once you have the trustline setup on your Ledger XRP wallet, you can send the ALV from your Gatehub wallet to your Ledger XRP wallet.  On Gatehub: 
(1) select the wallet that has your ALV;
(2) click the send payment link;
(3) enter the address of your Ledger XRP wallet as the destination (it uses the same address as if you were sending XRP); 
(4) in the amount field, be sure to **click the drop-down box and select ALV** as the currency then enter an amount you want to send and click "Next step"
(5) finish the transaction and your ALV should appear in your Ledger XRP wallet; verify new account balance on [xrpcharts.ripple.com](xrpcharts.ripple.com).

**Comment by gre** [comment] 2018-07-11 20:39
ok i found out a way. I've used the public seed `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about` to open a trustline. i'll investigate from this

**Comment by gre** [comment] 2018-07-12 13:42
🎉

**Comment by wehard** [comment] 2018-07-12 13:54
Nice, great job! 👍👌

**Comment by gre** [comment] 2018-07-12 13:55
thanks you guys for your help on this too :) if everything is good we should have the 1.0.2 tomorrow

**Comment by Errol1886** [comment] 2018-07-13 17:05
I just download the Ledger Live 1.02 desktop application update and I still can not add my XRP account that has a ALV token trustline assigned to it. There is now a new error message that pops up on the screen:

_**"Cannot read property address of undefined. Something went wrong. Please retry or contact us."**_

![ledger-live-1 02-add-xrp-account-error](https://user-images.githubusercontent.com/41203384/42704268-1f75ad9e-86c7-11e8-9dcd-0a842eb61413.jpg)

**Comment by meriadec** [comment] 2018-07-13 17:41
Looks like the fix wasn't enough because it filtered [only `trustline` typed txs](https://github.com/LedgerHQ/ledger-live-desktop/blob/5b2ffabc47ddd1504fb8482d2657224cfb88fd51/src/bridge/RippleJSBridge.js#L199) (enough to fix the problem on `abadon`). We may filter everything not containing `source`..

**Comment by meriadec** [comment] 2018-07-13 17:42
I admit it was a good move to not release too early, finally ;)

**Comment by ferozkhanhamid** [comment] 2018-07-14 07:33
I've had the error posted by @wehard with v1.0.0 and v1.0.1. But with v1.0.2, Ledger Live was able to read and sync my account. So the problem only persists when the a trustline is still open on a Ripple address. I've had a trustline open and token(s) on my address. I transferred the tokens and removed the trustline, and now v1.0.2 syncs my address. I'll still wait for a stable release to add it permanently though.

![screen shot 2018-07-14 at 12 57 42 pm](https://user-images.githubusercontent.com/41228015/42722233-46572e84-8766-11e8-86f1-a87772382489.png)

**Comment by ferozkhanhamid** [comment] 2018-07-14 07:41
@gre I'm happy to send some ALV for testing this, just lemme know where.

**Closed** 2018-07-16 11:43 UTC
Labels: bug
