### ISSUE TITLE
Poll the update availability

### ISSUE THREAD

**Issue by EricLarch** [LedgerHQ/ledger-live-desktop#1175] opened 2018-07-17 15:54 UTC
Most of the users never restart the application and keep it in the background. Therefore, the update notification may be lost for many and the installation base may keep stuck on old versions.

We should host the update API call on our infrastructure and poll it every X hours.

**Comment by gre** [comment] 2018-07-17 16:08
we don't need to host it in our infra because it directly works with Github. Yet, we can implement this feature without our infra ;)

**Comment by gre** [comment] 2018-07-17 16:09
to be confirmed

**Comment by EricLarch** [comment] 2018-07-20 08:17
Moving it to our infra would be to avoid DDOS Github with the high number of requets (don't know if we are rate limited on that). Also, it's always better to reduce third party dependancies by proxying this.

**Comment by gre** [comment] 2018-07-20 08:23
AFAIK:

- there is no rate limit on Github per project.
- there is a global rate limit on Github per IP tho.

i'm not sure what moving to our infra would mean, but probably lot of work (need to proxy the download of files, etc) but I agree it would be a plus to have a second source, e.g. in case github goes down.

I think for short term solution, we can look at polling github each hour or something like this.

**Comment by gre** [comment] 2018-07-23 12:30
plz see more general discussion https://github.com/LedgerHQ/ledger-live-desktop/issues/1243 :+1:

**Comment by gre** [comment] 2019-05-16 20:15
Fixed by now

**Closed by gre** 2019-05-16 20:15 UTC
Labels: enhancement, needs investigation
