### ISSUE TITLE
Faild to start on Fedora 29

### ISSUE THREAD

**Issue by paulsmicheli** [LedgerHQ/ledger-live-desktop#1773] opened 2019-01-28 15:58 UTC
#### Ledger Live Version and Operating System

- tested on Ledger Live **ledger-live-desktop-1.3.2-linux-x86_64.AppImage **
- Platform and version: **Fedora release 29 (Twenty Nine)**

#### Expected behavior

Application to Start 

#### Actual behavior

After making the AppImage executable (chmod+x or using GUI) starting the application (double click or ./ledger-live-desktop-1.3.2-linux-x86_64.AppImage in cli) application launches but all I get is spinning ledger logo. 

#### Steps to reproduce the behavior

Download AppImage on Fedora 29, make executable, start the application.

**Comment by meriadec** [comment] 2019-02-01 15:48
Reminds me the ledendary [#1010](https://github.com/LedgerHQ/ledger-live-desktop/issues/1010), looks like we still have problem with Fedora..

I've just installed Fedora 29 on a VM, and had no issue running Ledger Live. So again, the problem could occur only on upgraded Fedora (e.g from 28 to 29). Is it the case for you?

Also, to try to identify the cause, can you launch the app with `DEV_TOOLS=1` env var?

```bash
DEV_TOOLS=1 ./ledger-live-desktop-1.3.2-linux-x86_64.AppImage
```

and attach here any error logged into the console.

**Comment by paulsmicheli** [comment] 2019-02-01 15:56
Hi @meriadec 

I am running Fedora 29

Terminal output when using DEV_TOOLS=1

`$ DEV_TOOLS=1 ./ledger-live-desktop-1.3.2-linux-x86_64.AppImage                           
debug: 📁  read app:user {"type":"db","pname":"main","timestamp":"2019-02-01T15:50:31.079Z"}                           
debug: 📁  read windowParams:MainWindow.dimensions {"type":"db","pname":"main","timestamp":"2019-02-01T15:50:31.091Z"} 
debug: 📁  read windowParams:MainWindow.positions {"type":"db","pname":"main","timestamp":"2019-02-01T15:50:31.109Z"}  
debug: 📁  write windowParams:MainWindow.dimensions {"type":"db","pname":"main","timestamp":"2019-02-01T15:50:31.845Z"}
debug: 📁  write windowParams:MainWindow.positions {"type":"db","pname":"main","timestamp":"2019-02-01T15:50:31.845Z"} 
debug: 📁  write windowParams:MainWindow.dimensions {"type":"db","pname":"main","timestamp":"2019-02-01T15:50:59.816Z"}
debug: 📁  write windowParams:MainWindow.positions {"type":"db","pname":"main","timestamp":"2019-02-01T15:50:59.816Z"} 
debug: 📁  write windowParams:MainWindow.dimensions {"type":"db","pname":"main","timestamp":"2019-02-01T15:51:00.428Z"}
debug: 📁  write windowParams:MainWindow.positions {"type":"db","pname":"main","timestamp":"2019-02-01T15:51:00.429Z"} 
debug: 📁  write windowParams:MainWindow.dimensions {"type":"db","pname":"main","timestamp":"2019-02-01T15:51:00.924Z"}
debug: 📁  write windowParams:MainWindow.positions {"type":"db","pname":"main","timestamp":"2019-02-01T15:51:00.925Z"} 
debug: 📁  write windowParams:MainWindow.dimensions {"type":"db","pname":"main","timestamp":"2019-02-01T15:51:01.459Z"}
debug: 📁  write windowParams:MainWindow.positions {"type":"db","pname":"main","timestamp":"2019-02-01T15:51:01.459Z"} 
debug: 📁  write windowParams:MainWindow.dimensions {"type":"db","pname":"main","timestamp":"2019-02-01T15:51:03.899Z"}
debug: 📁  write windowParams:MainWindow.positions {"type":"db","pname":"main","timestamp":"2019-02-01T15:51:03.900Z"}`

This error is in the console log

'Uncaught Error: /tmp/.org.chromium.Chromium.nDJCh9: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_ledgerP10dmQ/app/resources/app.asar/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/tmp/.mount_ledgerP10dmQ/app/resources/app.asar/node_modules/usb/usb.js:526:3)'

**Comment by meriadec** [comment] 2019-02-01 16:05
Interesting. Given similar issues, e.g [node-sass#2043](https://github.com/sass/node-sass/issues/2043), [gulp-sass#521](https://github.com/dlmanning/gulp-sass/issues/521), you may give a try to add `exec` mount option in your `/etc/fstab` (I guess on your root partition) then reboot and try again.

**Comment by paulsmicheli** [comment] 2019-02-01 16:31
yes, yes, yes, I have a funny PCI compliant work laptop with funny boot permissions.

Thank you

**Comment by meriadec** [comment] 2019-02-01 16:42
Ahaharf... I know that feeling. So does it means it solved your problem? If yep, you can close the issue.

**Comment by paulsmicheli** [comment] 2019-02-01 16:43
Yea all solved, you can close.

Thank you

**Closed** 2019-02-01 16:44 UTC
Labels: needs investigation
