### ISSUE TITLE
Periodic wrong data on charts

### ISSUE THREAD

**Issue by Staffanox** [LedgerHQ/ledger-live-desktop#3148] opened 2020-09-01 18:55 UTC
#### App Version

Tested on  Ledger Version 2.11.0
Problem was persistent in earlier versions as well

#### Expected behavior
The chart for the value should have correct  data  all the time and show a fitting graph

#### Actual 

behavior

In seemingly random intervals the price of a cryptocurrency, in this example both Bitcoin and Chainlink seem to spike for a few days, don't move at all and then go back to their real price.

#### Steps to reproduce the behavior

I don't know how to reproduce it, it seems to be random, but the dates  on the screenshots might provide some more intel

![Bitcoin](https://user-images.githubusercontent.com/44144225/91894045-5810ce00-ec95-11ea-96ed-0cedc9ee5502.png)
![Chainlink](https://user-images.githubusercontent.com/44144225/91894048-58a96480-ec95-11ea-98e0-ed7c5f82f6c5.png)

**Comment by ErnestStaug** [comment] 2020-09-02 07:13
I am having same issues as well on mobile and desktop... 
![image](https://user-images.githubusercontent.com/17262977/91943231-e6706880-ed04-11ea-9dbe-a029a8fb88c1.png)

**Comment by dasilvarosa** [comment] 2020-09-14 14:09
Duplicate of https://github.com/LedgerHQ/ledger-live-desktop/issues/3122

**Closed by dasilvarosa** 2020-09-14 14:09 UTC
