### ISSUE TITLE
Error: Internal process error (3765269347)

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#974] opened 2018-07-09 17:35 UTC
![10-07-2018 030528](https://user-images.githubusercontent.com/41021204/42466396-27c4aaea-83f2-11e8-80f0-e2c9ed24f9fc.jpg)
Error was thrown:

```
Error
    at o (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25413)
    at a (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25600)
    at EventEmitter.l (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:27016)
    at emitTwo (events.js:130:20)
    at EventEmitter.emit (events.js:213:7)
```
![10-07-2018 030528](https://user-images.githubusercontent.com/41021204/42466451-53dfe054-83f2-11e8-87b3-841bca24c233.jpg)

**Comment by balthazar** [comment] 2018-07-09 17:38
Duplicate of #933.

**Closed** 2018-07-09 17:40 UTC
