### ISSUE TITLE
Ledger Live not syncing ZEC

### ISSUE THREAD

**Issue by Derpalupagus** [LedgerHQ/ledger-live-desktop#1643] opened 2018-11-14 22:44 UTC
ZEC transactions not syncing for several days on Ledger Live 1.2.3, Windows 10 on 2 separate computers.  System hangs on "Synchronizing" and times out.  Every retry times out as well.  I have the latest apps installed.  Other coins sync normally.

NOTE:  I am mining to this ZEC address but this is a new issue that has only been happening for the 5 days or so.  Previously there were no sync issues for any coins. 

I've tried wiping everything (clear the cache, reset Ledger Live, delete the folders, uninstall and then reinstall).  Still no reliable ZEC sync.  No adequate response from Ledger Tech Support on ticket 226426.

**Comment by Transisto** [comment] 2019-01-06 00:39
They can barely support Bitcoin properly, Stop distracting them with your garbage.

**Comment by cthepot-ledger** [comment] 2020-09-11 15:50
Duplicate of #1439

**Closed by cthepot-ledger** 2020-09-11 15:50 UTC
Labels: bug, needs investigation
