### ISSUE TITLE
Countervalue for NOK not working

### ISSUE THREAD

**Issue by NicTorgersen** [LedgerHQ/ledger-live-desktop#2669] opened 2020-03-04 16:54 UTC
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.0.0**
- Platform and version: **Windows 10**

#### Expected behavior

I expect countervalues for Norwegian Krone to work, but they don't. USD works.

#### Actual behavior

Nothing is displayed at all.
![image](https://user-images.githubusercontent.com/1327106/75902903-0f409f80-5e41-11ea-9431-45367511ba61.png)

#### Steps to reproduce the behavior

Go to Settings->Countervalue, set to Norwegian Krone, go to Portfolio and watch as no currency values are displayed.

**Comment by d-rez** [comment] 2020-03-10 01:11
Same for AUD

**Comment by cthepot-ledger** [comment] 2020-09-15 15:46
Duplicate of #2326

**Closed by cthepot-ledger** 2020-09-15 15:46 UTC
