### ISSUE TITLE
Memos for Individual Transactions

### ISSUE THREAD

**Issue by ctrl-reset** [LedgerHQ/ledger-live-desktop#2497] opened 2019-11-27 02:16 UTC
I would love to see an update for ledger live, that allows me to create a memo for each transaction sent or received, so I can always look back and track where that transaction came from or went. Color coding and then sorting by memo or color could be useful as well.

**Comment by cthepot-ledger** [comment] 2020-09-15 12:26
Duplicate of #1079

**Closed by cthepot-ledger** 2020-09-15 12:26 UTC
