### ISSUE TITLE
Exchange Rate support for Any ETH Token

### ISSUE THREAD

**Issue by coltonfisher** [LedgerHQ/ledger-live-desktop#3082] opened 2020-07-18 20:46 UTC
There are many ETH tokens that do not have a price in Ledger Live and therefore cannot track the true value of the portfolio. Is there any chance of adding manual exchange rates for tokens that do not have an exchange linked to the ledger live price tracking system. Or perhaps add some additional exchanges. I'm concerned specifically with the value of compound tokens like cBAT, cETH, etc. Really I just want the system to be able to convert cBAT, cETH, etc tokens back into their true currency - e.g. BAT, ETH, etc.

**Comment by cthepot-ledger** [comment] 2020-09-17 17:09
Duplicate of #2326

**Closed by cthepot-ledger** 2020-09-17 17:09 UTC
