### ISSUE TITLE
Generate batches of addresses for better BtcpayServer integration

### ISSUE THREAD

**Issue by bitstein** [LedgerHQ/ledger-live-desktop#1472] opened 2018-08-29 17:16 UTC
- [x] I have checked this feature was not yet requested.

Ledger has a fantastic integration on BtcpayServer. However, on BtcpayServer, an account will be generating many addresses for invoices that are ultimately not fulfilled, leaving many large gaps before the next address with associated UTXOs. It would be nice to have a way to mark an account as associated with BtcpayServer, so you can generate more addresses until it is in line with what you see on your account on the server. Currently, this must be done more manually via a wallet such as Electrum.

#### Part of the application

Account management

**Comment by 2pac1** [comment] 2018-11-08 10:50
Ledger, please make this happen as soon as possible.

**Comment by cthepot-ledger** [comment] 2020-09-11 15:33
Duplicate of #1079

**Closed by cthepot-ledger** 2020-09-11 15:33 UTC
Labels: feature request

**Comment by cthepot-ledger** [comment] 2020-09-11 15:34
Duplicate of #1166
