### ISSUE TITLE
Republic Protocol does not have value / price

### ISSUE THREAD

**Issue by marbew** [LedgerHQ/ledger-live-desktop#3100] opened 2020-07-29 12:36 UTC
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.8
- Platform and version: Linux Ubuntu desktop 20.04

#### Expected behavior

It should show the price associate and the value in the right column.

#### Actual behavior

It does have an empty field for value and for price columns.

#### Steps to reproduce the behavior

Just open the ledger-desktop app on Linux Ubuntu.

**Comment by cthepot-ledger** [comment] 2020-09-18 08:37
Duplicate of #2326

**Closed by cthepot-ledger** 2020-09-18 08:37 UTC
