### ISSUE TITLE
Select specific address to send from

### ISSUE THREAD

**Issue by tsujp** [LedgerHQ/ledger-live-desktop#1611] opened 2018-10-29 14:27 UTC
**- [X] I have checked this feature was not yet requested.**

To the best of my knowledge.

#### Accounts/Send

We should be able to specify (if we want to) specifically the address we're sending assets from, instead of having the software pick and choose a mix of addresses for us.

Yes you can send the exact amount and it forces the software to use that specific address but having to search on a blockexplorer _exactly_ how much I have in an address just to force-use that address (and it may not be the entire amount I desire) is not user friendly.

#### Part of the application

Accounts/Send

**Comment by graemeblackwood** [comment] 2019-01-17 11:41
This should be possible at least for BTC and ETH.

**Comment by hito** [comment] 2019-01-17 18:00
I should also mention I use the Chrome application because that is LIFO and Ledger Live is FIFO. We should have the option to select this also. All in all there is no fidelity for controlling which addresses are selected, and when hosting ZEN nodes I found that addresses with the stakes in them constantly got interrupted by Ledger Live so I am forced to keep Chrome installed and use the Chrome Ledger Wallet app to force it to use the last VINs for VOUTs and I must use a script to calculate the amounts I can send out with 0 fees so I can select exactly the amounts I want.

This isn't friendly for management of assets in that manner yet, and I fully acknowledge this is a nice request for probably 99% of the userbase.

**Comment by Flydancer** [comment] 2020-06-13 00:19
Yes, please! I don't get it how such an expensive product like ledger doesn't even have the most simple features every other wallet on earth has.

**Comment by cthepot-ledger** [comment] 2020-09-11 15:45
Duplicate of #1234

**Closed by cthepot-ledger** 2020-09-11 15:45 UTC
Labels: feature request
