### ISSUE TITLE
OXT Price not shown

### ISSUE THREAD

**Issue by bmxorcist** [LedgerHQ/ledger-live-desktop#2831] opened 2020-04-08 17:03 UTC
#### Ledger Live Version and Operating System

- tested on  Ledger Live 2.0.1

- Platform and version: Windows 10

#### Expected behavior

OXT value in USD should be visible and count towards total account balances.

#### Actual behavior

I can see my OXT balance, but not my USD value. 

![Capture1](https://user-images.githubusercontent.com/6394490/78812323-1434c980-7980-11ea-88e1-01e7d811db31.PNG)

#### Steps to reproduce the behavior

Open OXT wallet, or view OXT on Portfollio, or Accounts summary.

**Comment by cthepot-ledger** [comment] 2020-09-16 13:58
Duplicate of #2326

**Closed by cthepot-ledger** 2020-09-16 13:58 UTC
