### ISSUE TITLE
Add scroll bars

### ISSUE THREAD

**Issue by maxocoin** [LedgerHQ/ledger-live-desktop#1072] opened 2018-07-11 23:43 UTC
I have to use a mix of keystrokes and mouse clicks for reaching the non visible parts of the window.

Could you add some scroll bars to the main window?

**Comment by meriadec** [comment] 2018-07-12 09:25
💯 for this.

We ran into diverses solutions with scrollbars, from custom libraries to hiding them completely for design purposes 😄 , IMO it's a bad idea and a complete accessibility loss.
It's actually in discussion, I have POC on my side of native scrollbars customized via CSS, which is pretty acceptable. Keep updated.

**Comment by jdevora** [comment] 2018-07-17 11:00
I saw many programs that only show the scroll bars when you hover over the area...
Will that keep the designers happy? ;-)

**Comment by gre** [comment] 2018-07-17 11:46
the problem is not designers, it's us, developers . it's actually tricky to get something customizable AND performant.
we've tried a JS based scroll implementation ( https://github.com/idiotWu/react-smooth-scrollbar ) and it was really not good. we're looking at a pure CSS solution now.

(needs to not run in JS thread basically)

**Comment by gre** [comment] 2020-02-20 15:43
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596

**Closed by gre** 2020-02-20 15:43 UTC
Labels: design
