### ISSUE TITLE
Wrong device or passphrase error before signing the transaction.

### ISSUE THREAD

**Issue by cryptot27** [LedgerHQ/ledger-live-desktop#2047] opened 2019-06-02 15:03 UTC
Dear ledger support,

I have exactly the same issue as 1jjhollywood in the following thread:
https://github.com/LedgerHQ/ledger-live-desktop/issues/1851

Unfortunately, that thread is closed without the resolution being posted.

When sending out Vertcoin, I see the following error.
![ledger snip](https://user-images.githubusercontent.com/39165823/58763138-45768900-8568-11e9-9e66-2995bc63d12b.jpg)

#### Ledger Live Version and Operating System

- tested on Ledger Live 1.9.1
- Firmware: 1.5.5
- Platform and version: Windows 10 

#### Expected behavior

I expect that I can send the coins

#### Actual behavior

I received this error message before I could sign the transaction on my ledger.
This is a genuine ledger (bought from your company directly), never changed the seed or pin. Have used the Ledger before without issues with the same device, same seed and same pin.
Ledger Live is synchronising my balances correctly.

#### Steps to reproduce the behavior

Please provide me with the solution for issue 1851 as I seem to have exactly the same problem.

**Comment by gre** [comment] 2019-06-02 15:53
#1851 was solved because user was not using the account added from the same seed which is what this error is telling.

There is however one rare bug we're aware but never was able to understand nor reproduce: sometimes account data get swapped (e.g. Account 1 is swapped with Account 2 but Ledger Live still have part of the old data of the other account)

If you tell me you are sure this is using the same seed as the account imported (aka when you do Add Accounts on Vertcoin with your device, you see the same "already imported" accounts), the only thing that would solve that "rare bug" would be to remove all Vertcoin accounts from Ledger Live, do a "Clear Cache" and import them all again.

thanks

**Comment by cryptot27** [comment] 2019-06-03 20:21
Thanks, the solution provided worked (removed the coin accounts, cleared
cache and reinstalled the amounts).

Appreciate the swift and adequate support provided on this issue.

**Comment by gre** [comment] 2019-06-04 05:08
@cryptot27 Could you answer the two questions I had at the end to try to see if there is a pattern for this issue? We're having hard time understanding how to get into this issue.
Thanks

**Comment by cryptot27** [comment] 2019-06-04 08:23
Sorry, I have missed those questions in your first response. However, I
have ever only setup one seed and one account with my ledger and ledger
live. Hope this answers your question. If not, please let me know what
additional info you need and I am happy to help debugging.

**Comment by cardave1956** [comment] 2019-10-07 16:57
I am now having the same issue..I tried accessing Ledger live on my other computor and it asked me to set up my device..which I did using the same passphrase and pin as when I set it up on my laptop.  I can see the balances on the lap top Ledger Live, but cannot see the balances when I log in on my other computor..I keep getting an error message see below...I have not nor have never changed my passphrase.  How do I access my cryptos??
<img width="477" alt="Screenshot 2019-10-07 11 26 50" src="https://user-images.githubusercontent.com/56269770/66332161-0e432a80-e902-11e9-84ea-69107cbb00ba.png">

**Comment by gre** [comment] 2019-10-07 18:53
By passphrase do you mean your 24-words? 

There are two reason this error can happen:
- either you use a device with a seed (24 words/passphrase if any) that is unrelated to the account
- either there is something wrong with the ledger live data. Potentially a bug.


Assuming you are not in the first case, please (1) try to Add Accounts again with that device, does that help discovering the same account (they should appear in already imported section). (2) please try to do a clear cache in ledger live desktop. (3) please try to completely reimport the accounts by removing manually the problematic account, do a clear cache and adding them again.

Let us know which option worked.

It would be interested to know on which derivation path the account is (possible to see in account settings, advanced options)

**Comment by cardave1956** [comment] 2019-10-07 19:03
I’m afraid to do anything as I don’t want my funds lost. Can that happen if they don’t show up on ledger live? 

Sent from my iPhone
Carol Braund

**Comment by cardave1956** [comment] 2019-10-07 19:04
Also what if by chance I’m using the wrong pass phrase.  

Sent from my iPhone
Carol Braund

**Comment by cardave1956** [comment] 2019-10-07 19:24
This morning I wanted to access my crypto from a different computer so I downloaded ledger live onto that computer and plugged in my device. It asked me what I wanted to do and I put add a already initialized device. And it asked me for pin and 24 word pass phrase which I put in. I then added accounts but only zeros came up in those accounts.  I then tried to access my ledger live account from my original computer that was actually showing my balances. When I tried to receive or send funds it kept giving me the error saying this device was not associated with this account. It worked fine before I set up another live ledger Acct on second computer.

However this is the first time I’ve used my 24 pass phrase when i added the ledger nano to the new ledger live on second computer. I may have written pass phrase down. wrong???  I don’t know but freaking out as I cannot get my funds. Please advise 

Sent from my iPhone
Carol Braund

**Comment by gre** [comment] 2019-10-07 19:31
If you are in control of your 24 words and you send funds on the address that was displayed and confirmed on the device there is nothing to worry. If you never changed your 24 words, it should be fine. You can't lose anything on Ledger Live itself as everything is backed by the device and in fine by the 24 words.

To me if the same accounts does not show up in another instance of Ledger Live it could mean you do not use the same 24 words.

Please contact our tech support team that will help you more on investigating. https://support.ledger.com/hc/en-us/requests/new

(We don't generally provide support over GitHub as only developers are on this platform)

**Comment by cardave1956** [comment] 2019-10-07 21:01
Thank you I found the correct passphrase..it works now..I had a decoy in the box.

Carol Braund

**Comment by gre** [comment] 2019-10-08 06:46
Ok thanks.

I'm closing this issue until we have an exact way to reproduce the problem (if a bug exists there). It appears most case it was just user side problem with using a wrong device/wrong seed/wrong passphrase.

**Closed by gre** 2019-10-08 06:46 UTC
