### ISSUE TITLE
AUD - Countervalue

### ISSUE THREAD

**Issue by stuartscott171** [LedgerHQ/ledger-live-desktop#2859] opened 2020-04-16 08:32 UTC
Latest update has made AUD - Countervalue no longer available

**Comment by gre** [comment] 2020-04-16 10:50
we are planning to add it back as soon as we have better countervalues API.

**Comment by stuartscott171** [comment] 2020-04-16 10:51
Ok thank you for the feedback.

**Comment by cthepot-ledger** [comment] 2020-09-16 16:07
Duplicate of #2326

**Closed by cthepot-ledger** 2020-09-16 16:07 UTC
