### ISSUE TITLE
Add support for Wasabi Wallet addresses

### ISSUE THREAD

**Issue by JazzBashara** [LedgerHQ/ledger-live-desktop#1743] opened 2019-01-13 15:22 UTC
Future idea to add support for Wasabi Wallet addresses.
https://www.wasabiwallet.io/

**Comment by kirillkovalenko** [comment] 2019-01-22 10:37
The address format wassabi wallet uses called [Base32 address format for native v0-16 witness outputs](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki). This issue is basically a duplicate of #1051.

**Closed** 2019-01-22 13:42 UTC
