### ISSUE TITLE
(unconfirmed) possible change in password decryption?

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1184] opened 2018-07-18 10:06 UTC
it is being raised that people having difficulty unlocking (password is incorrect) after updating the app.
we need to make sure the decryption is stable over time.
But first we need to try to reproduce the problem to make sure it's not an user issue.

**Comment by NastiaS** [comment] 2018-07-18 16:20
I couldn't reproduce this issue on my side. I tried:

For Mac and Windows 10

- Install 1.0.1 version -> setPassword -> update the app to 1.0.3 -> unlock

- Install 1.0.2 version -> setPassword -> update the app to 1.0.3 -> unlock

In all cases I tried letters, numbers, all kinds of special chars (@#$%^~`|\''?""()& and special letters like ë,è,á and so on), also white spaces, capital letters. 
I tried to setPassword from both Onboarding and Settings 
None of those scenarios gave me Incorrect Password error if password is typed correctly 

If there are more scenarios I can try it, but so far I can't see this issue on my side.

**Comment by gre** [comment] 2018-07-18 16:23
ok. I suspect either wrong password was inputed OR user touched one of the user data file that corrupted its data.
closing until someone detail a reproductible plan.

**Comment by dogcowuk** [comment] 2018-07-18 17:54
I logged into Ledger Live ok then did update then could no longer use the same password as getting the "password is incorrect" message and this is not user error as i tested many times.
I am using Mac OS 10.11.6 on MCP.
I have not yet tried resetting Ledger Live and typing in a new password but wanted to verify that i too am having this issue after recent update.

**Comment by gre** [comment] 2018-07-18 18:41
this is really weird. I wonder if Electron update mess up something during the upgrade process 🤔

**Comment by gre** [comment] 2018-07-18 18:48
@dogcowuk you confirm you have not touched at all the files like `accounts.json` etc ?

**Comment by NastiaS** [comment] 2018-07-18 18:56
I do have a newer Mac and I tested on it, we do have 1 older desktop in the office, maybe we can try tomorrow

**Comment by dogcowuk** [comment] 2018-07-18 19:18
Re: "If the funds on the Ledger device were from a pre-overwinter z-address to t-address utxo, meaning someone sent funds to their Ledger (before overwinter activated) from a shielded address, that transaction fails to be sent out."
N.B. I was in the process of sending ETH to my ledger address before the update had completed, not sure if this is related or not?

**Comment by gre** [comment] 2018-07-18 19:22
@dogcowuk wrong issue :)

**Comment by gre** [comment] 2018-07-18 19:23
> N.B. I was in the process of sending ETH to my ledger address before the update had completed, not sure if this is related or not?

Mmh we might have to take a look for potential race conditions, but normally we should not have such issues.. i've double checked in the code and an update is not supposed to affect in any way the way data are encrypted and decrypted!

**Comment by dogcowuk** [comment] 2018-07-19 11:51
@gre 
accounts.json file is unreadable, encrypted, obfuscated.
migration.json, settings.jason, user.json files are readable
Logs - log file: 

65536,"stringVersion":"1.0.0","level":"info","message":"libcore","pname":"renderer","timestamp":"2018-07-19T11:36:12.699Z"}
{"0":"T","1":"r","2":"a","3":"n","4":"s","5":"l","6":"a","7":"t","8":"e","9":"d","10":"E","11":"r","12":"r","13":"o","14":"r","15":" ","16":"i","17":"n","18":"v","19":"a","20":"l","21":"i","22":"d","23":" ","24":"u","25":"s","26":"a","27":"g","28":"e","29":":","30":" ","31":"T","32":"h","33":"e","34":" ","35":"p","36":"a","37":"s","38":"s","39":"w","40":"o","41":"r","42":"d","43":" ","44":"y","45":"o","46":"u","47":" ","48":"e","49":"n","50":"t","51":"e","52":"r","53":"e","54":"d","55":" ","56":"i","57":"s","58":" ","59":"i","60":"n","61":"c","62":"o","63":"r","64":"r","65":"e","66":"c","67":"t","level":"error","pname":"renderer","timestamp":"2018-07-19T11:36:13.578Z"}
{"type":"action","level":"debug","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-19T11:36:14.377Z"}
{"type":"action","level":"debug","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-19T11:36:16.251Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (null)","name":"InternalError"},"level":"warn","message":"✖ CMD listenDevices error","pname":"renderer","timestamp":"2018-07-19T11:36:18.568Z"}
{"message":"listenDevices error","name":"InternalError","level":"warn","pname":"renderer","timestamp":"2018-07-19T11:36:18.571Z"}
{"type":"action","level":"debug","message":"⚛️  RESET_DEVICES","pname":"renderer","timestamp":"2018-07-19T11:36:18.571Z"}
{"type":"cmd.START","level":"info","message":"CMD listenDevices.send()","pname":"renderer","timestamp":"2018-07-19T11:36:18.579Z"}

**Comment by gre** [comment] 2018-07-19 17:51
@dogcowuk Ok, and I guess you checked the file state while still being in this locked state? I was thinking it could have been that the accounts.json gets unencrypted while the app still try to decrypt it but it must be something else.
You also seem to have `✖ CMD listenDevices error` which indicates another issue.

on which OS / version are you on?

I hope we can figure out this bug, because so far we have not succeed to reproduce it (even tried to downgrade to different versions..)

I'm afraid you might have to reset the app as workaround until we find the problem.

**Comment by dogcowuk** [comment] 2018-07-19 17:56
@gre 
Max OS X El Capitan 10.11.6
MBP 15" Mid 2009
2.8 ghz Intel Core 2 Duo

I was waiting to see if I could be of any more help, I will reset the app and try again shortly.

**Comment by gre** [comment] 2018-07-19 17:58
We have discovered a bug in older mac version that will probably fix this crash so it might be helpful to test on next 1.0.4 we'll do. even tho i don't see how it could be related to the present bug tho.
this bug has been raised by some users from different OSs (linux, windows too)

**Comment by dogcowuk** [comment] 2018-07-19 18:40
RE: > I'm afraid you might have to reset the app as workaround until we find the problem.

FYI: Reset was successful with no issues, hopefully will not need to reset again after the next update.

**Comment by gre** [comment] 2018-07-19 19:14
thanks. please don't hesitate to ping us here if you see problem again, more detail we'll have and better it will be to identify the root of the problem. 👍

**Comment by gre** [comment] 2018-07-20 16:32
one simple way to reproduce it on Windows (beware you will lose your app data):

- Open settings.json file of the app on Notepad. windows will prevent the app to save again the file because it is opened and can't be renamed. (this is how electron store manage saving, by renaming the file, via the usage of pkg `write-file-atomic` , it's not a so bad idea, **but it is not guarantee to be successful**)
- change your password.
- quit the app
- quit your Notepad

now open again the app. you must reproduce the present bug

**Comment by mjansing** [comment] 2018-07-25 09:52
I ran into the same issue. Updated Ledger Live from 1.0.1 to 1.0.3 on macOS and now I'm not able to unlock it.

**Comment by punkay** [comment] 2018-07-26 21:29
does the program update automatically? anyways, i didn't update and just today my password was told to be wrong. i am absolutely sure that it was NOT wrong, and i also didn't mess with any files. i had to reset ledger live. scared the sh** out of me!

**Comment by meriadec** [comment] 2018-07-26 21:42
Yep sorry about that :( In some cases, the self-update alter the encrypted file, and the password hash doesn't match anymore. We're currently working on a fix. Keep in mind that the app password is about privacy, not security, and that your funds are secured by your device.

**Comment by gre** [comment] 2018-07-27 05:00
@punkay there are 1000 reasons you could fall into the bug, it's not that related to the "update". I think the fact update will stop and restart straightaway the app is a case that make the bug appears more often.

In the meantime you will have to reset the app if the bug happen.. and import accounts again.
Hopefully bug is fixed soon

**Comment by wlloydda** [comment] 2018-07-27 15:33
Windows 10

I have switched back and forth from v1.0.1 to v1.0.3 many, many times.  My password ALWAYS works on v1.0.1; my password NEVER works on v1.0.3 (v1.0.2 also fails).

**Comment by gre** [comment] 2018-07-27 15:34
@punkay  we'll make the problem no longer auto update, but manual action from user in the future. #1243

**Comment by punkay** [comment] 2018-07-27 15:53
i did NOT have a problem. i'm really sorry. i typed the wrong password. i'm stupid. again, excuse me for causing trouble.

**Comment by rreiner** [comment] 2018-07-29 17:40
Having the same issue after Ledger Live autoupdate on Windows 10.

**Comment by meriadec** [comment] 2018-07-30 12:04
closed in https://github.com/LedgerHQ/ledger-live-desktop/pull/1297

**Closed by meriadec** 2018-07-30 12:04 UTC
Labels: bug, needs investigation
