### ISSUE TITLE
PROBLEM! Allow Ledger Manager on your device

### ISSUE THREAD

**Issue by miruashvili** [LedgerHQ/ledger-live-desktop#1748] opened 2019-01-16 20:12 UTC
I can't connect to Ledger Manager in Ledger Live.

I can still connect to my wallet to send and receive payments, but I can't install/unistall apps.

see screenshot
![1a](https://user-images.githubusercontent.com/44260773/51275822-6b9df100-19ec-11e9-9864-1cbe87825996.png)

Any solution? I already tried all USB ports and different cables.

**Comment by Chrysen** [comment] 2019-01-16 20:49
Same error
After Ledger Live Update, I can not log in anymore.
With the same error message.
Sometimes I can confirm the access on the ledger, but it does not start anyway.
Have testet  two Ledger Nano S, as well as several USB cables, ports and even starting with admin rights does not help.
Even reinstalling or restarting does not help.

**Comment by Luuk2016** [comment] 2019-01-16 20:58
Ledger's response on Twitter:
https://twitter.com/LedgerHQ/status/1085607408150298629

**Comment by gre** [comment] 2019-01-16 21:12
Thanks @Luuk2016 . Nothing that can be fixed on the LL side I'm afraid. Infra team is working on it. Thanks for your patience

**Closed by gre** 2019-01-16 21:12 UTC

**Comment by Chrysen** [comment] 2019-01-16 21:36
Thanks for info mh Same Error with older Ledger Live Version. 1.2.7

**Comment by Luuk2016** [comment] 2019-01-16 21:50
@Chrysen Ledger Live isn't the problem, there is a server problem.

**Comment by Neynko** [comment] 2021-02-06 15:13
It's 2021, but I ran into this issue in Win10. What I did is that I went into Devices and I pressed Delete at Nano S, (but it is in use, so it cannot be deleted,) than I returned to the Ledger App and pressed Retry as long as it allowed me to continue. I hope this helps some of you, because it somehow solved my problem.
