### ISSUE TITLE
Please add support for Binance Chain (BEP2)

### ISSUE THREAD

**Issue by aliuccio** [LedgerHQ/ledger-live-desktop#3437] opened 2021-01-05 08:38 UTC
Due to the high price of Ethereum and Bitcoin, the transactions on those blockchains got quite expensive. It would be great if Ledger can add support for Binance Chain (BEP2) on which the transactions cost only a fraction. I believe it would give you a great competitive edge over the other wallet makers.
Thank you for your great product.

**Comment by adamvp** [comment] 2021-01-23 22:52
You can use binance  chain via MEW (my ether wallet)

**Comment by schmitmd** [comment] 2021-02-21 21:27
This might be a duplicate of #3181 .  

As for using your Ledger with Binance chain, their [documentation is pretty good](https://docs.binance.org/smart-chain/wallet/ledger.html). 

That said, this issue was created in the Ledger Live Desktop repo, so I would assume that you want to track your balances and such inside Live itself like you can with Bitcoin/Ether/etc.  I too would like to see this in Ledger Live.  I imagine it could work pretty similarly to Ethereum in Live, where you have your main eth addr listed and ERC-20s tagged to that.  ...just with BEP-2 instead. I'm not a super skilled developer though and have no idea how much brain damage implementation might be.

**Comment by aliuccio** [comment] 2021-02-21 21:33
Hi Michael, exactly. I'd like to track the tokens I have on BEP2 or BEP20 on ledger live exactly the way I can see ERC-20 tokens.

**Comment by schmitmd** [comment] 2021-02-21 22:06
I feel like this is actually two major asks instead of one.  Given that BEP-2 and BEP-20 are on completely different blockchains, you'd have to make sure addresses stay in their lane. Nobody wants "oops, wrong chain" coin loss. 
Probably wouldn't be too bad, since Binance chain addrs all start with `bnb` and Smart chain ones can be `0x...`  

I realized that Live already supports this sort of thing though, with the Tron network (and others) so maybe it wouldn't be _too_ difficult...?

**Comment by aliuccio** [comment] 2021-02-21 22:22
Well, I think if we can get BEP20 (BSC) on ledger live, that is more than enough for now. I noticed that other famous wallets in the market (Trust Wallet or Metamask for example) implemented BEP20. Thanks.

**Comment by cthepot-ledger** [comment] 2021-02-26 20:50
Hi @aliuccio thanks for opening the issue. The request is tracked but is not scheduled for release. The issue is indeed a duplicate of #3181 as @aliuccio reported.

**Closed by cthepot-ledger** 2021-02-26 20:50 UTC
