### ISSUE TITLE
Plausible deniability

### ISSUE THREAD

**Issue by Oliver917** [LedgerHQ/ledger-live-desktop#3411] opened 2020-12-23 12:47 UTC
Not sure if it was a good idea to reply to an ancient issue https://github.com/LedgerHQ/ledger-live-desktop/issues/954 (labled 'discussion'), so creating a new issue. 

Now that everyone remotely interested has our residential address, plausible deniability should get a million billion times more priority.

At the very least make an implementation using multiple ledgers. e.g.:

- Mobile: Show different accounts (associated to different ledger(s)) based on pin / password . Pin/Password decrypts data. Find a way to plausibly deny that other 'real' accounts exist. E.g. always create 100 'instances' with random data, indistinguishable from encrypted data (a core characteristic of modern ciphers)
- Desktop: Like mobile, but also make ledger live portable, allow for multiple (USB thumbdrive) installs. (The workaround of creating multiple ledger live Operating System users is not sufficient.)

I know this may not be an easy problem to tackle, but the risk of home robbery had to be addressed at some point anyway. The hack just means it has to be done faster. Much faster.

**Comment by cthepot-ledger** [comment] 2020-12-23 14:38
@Oliver917 Thanks for your feedback. Taking the liberty to close this issue in order to track the number of requests within the same issue for sorting purposes. 
I understand plausible deniability is a subject of today, and appreciate the feedback shared.

**Comment by cthepot-ledger** [comment] 2020-12-23 14:39
Duplicate of #954

**Closed by cthepot-ledger** 2020-12-23 14:39 UTC
