### ISSUE TITLE
Please add KUSAMA full Support Wallet!

### ISSUE THREAD

**Issue by gushani** [LedgerHQ/ledger-live-desktop#3721] opened 2021-04-05 10:06 UTC
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

**Comment by gushani** [comment] 2021-04-05 10:07
Thanks

**Comment by cthepot-ledger** [comment] 2021-07-14 13:34
Duplicate of #3676

**Closed by cthepot-ledger** 2021-07-14 13:34 UTC
Labels: token support
