### ISSUE TITLE
Make the Portfolio screen graphs actually useful

### ISSUE THREAD

**Issue by mluczak** [LedgerHQ/ledger-live-desktop#1478] opened 2018-09-03 14:24 UTC
- [X] I have checked this feature was not yet requested.

The current way the graphs and portfolio evolution are shown is confusing because it mixes coins values and coins amount. It would be nice to have a separate view of the amount of coins and of the valuation. One possibility would be to be able to set BTC (or other) as the base currency and/or overlay this graph with the FIAT graphs.

#### Part of the application

Portfolio and accounts

**Comment by MortalKastor** [comment] 2018-09-03 14:43
Related: #1429

**Comment by cthepot-ledger** [comment] 2020-09-11 15:36
Duplicate of #1429 
my POV

**Closed** 2020-09-11 15:36 UTC
Labels: enhancement
