### ISSUE TITLE
Ledger Nano S - Device not recognized on Ubuntu

### ISSUE THREAD

**Issue by sarcos** [LedgerHQ/ledger-live-desktop#1582] opened 2018-10-15 18:12 UTC
Ledger Nano S

- tested on Ledger Live 1.2.0
- Platform and version: Ubuntu 14.04.5

Hello,
Ledger Live is stuck on 'Connect and unlock your Legder Device'
Tried, the udev rules, different USD port, running as sudo...

DEV_TOOLS output : 
warn: Command error: {"pname":"internal","timestamp":"2018-10-15T18:08:16.640Z"}
warn: ✖ CMD listenDevices error {"type":"cmd.ERROR","data":{},"pname":"internal","timestamp":"2018-10-15T18:08:16.640Z"}

its looping on those lines

Any idea ?
Thank you

**Comment by meriadec** [comment] 2018-10-15 18:41
Can you try to run the app with the `DEV_TOOLS` env var?

```
$ DEV_TOOLS=1 ./ledger-live-desktop-1.2.0-linux-x86_64.AppImage
```

It should open dev tools when app starts and show eventual error. I guess here the problem is with Ubuntu 14 (we support from Ubuntu 16.10), and probably incompatible GLIBC version.

**Comment by sarcos** [comment] 2018-10-15 19:01
thx, its seems you are right : 

Error {message: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version … (required by /tmp/.org.chromium.Chromium.4L1oyl)", name: "Error", stack: "Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: v…ainCallback (internal/process/next_tick.js:218:9)"}message: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.4L1oyl)"name: "Error"stack: "Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.4L1oyl)↵

**Comment by meriadec** [comment] 2018-10-17 13:51
Closing this, because for now we don't plan to support Ubuntu < 16.04. You may want to upgrade system or maybe compile the app on your side (see README), but I'm not sure our libcore dependency will be compatible.

**Closed by meriadec** 2018-10-17 13:51 UTC
