### ISSUE TITLE
Choose output address manually

### ISSUE THREAD

**Issue by LedgerUser1** [LedgerHQ/ledger-live-desktop#1234] opened 2018-07-20 17:23 UTC
- [x] I have checked this feature was not yet requested.

DESCRIPTION: Explain precisely what is the feature about →

Choose output address manually for example to keep addresses separated on the blockchain.

#### Part of the application

Interface

**Comment by cthepot-ledger** [comment] 2020-09-10 16:16
Duplicate of #1294

**Closed by cthepot-ledger** 2020-09-10 16:16 UTC
