### ISSUE TITLE
Peercoin fees are 0.01 ppc per kb, rounded up

### ISSUE THREAD

**Issue by backpacker69** [LedgerHQ/ledger-live-desktop#1377] opened 2018-08-04 12:46 UTC
Peercoin fees are 0.01 ppc per kb, rounded up. currently live app makes underfunded transactions that are rejected by the peercoind daemon, as minimum txn fee is 0.01 ppc

**Comment by jimisan** [comment] 2018-08-16 09:38
so ledger, would you like to tell, what you gonna do? :) I send a lot of ppc and it stucks. please, help.

**Comment by gre** [comment] 2018-08-16 19:35
this is a problem at the nodes/explorer level. not at Ledger Live level. 

not exactly sure if it's easy to fix, but it's likely we want to adjust and maintain better the fees. also we need to have different fees (for slow/medium/fast). I think the hardcoded fees happen only when we can't retrieve it from network, in such case I would suggest we do something like slow=1x medium=1.5x fast=2x , or some scalar factor like this.. or we maintain all levels ourself but we need them different too.

cc @tt810

**Comment by peerchemist** [comment] 2018-08-16 20:02
> not exactly sure if it's easy to fix

It's quite simple, just start paying the right fee.

> in such case I would suggest we do something like slow=1x medium=1.5x fast=2x

Increasing the tx fee won't make it go faster in Peercoin. First come, first served.

Basic variables:

* MIN_FEE is 0.01
* cost per tx is 0.01 PPC per kB

0.01 PPC will do for most of the transactions.

**Comment by gre** [comment] 2018-08-17 08:46
@peerchemist ok thanks for the detail. I was not familiar with peercoin specifics :) i'll make sure the api team is aware of this. (when i'm back from holidays 🍸😉)

**Comment by jimisan** [comment] 2018-08-17 10:12
@gre. Cool. You just wasn't familiar with peercoin specifics. Excuse me, but I bought device from you, I used your software and this is your fault as a company too (be such ignorant on specifics of released non beta, non alpha software), imo. Also this situation is similar to $eth static address bug on your chrome app.  It's a problem on your application, it's bug, imperfection.  I suffered a lot. Thank you for this experience.

**Comment by jimisan** [comment] 2018-08-17 11:00
@gre , "this is a problem at the nodes/explorer api level. not at Ledger Live level." --> I inputted values in the ledger live app interface. You should fix this, to prevent wrong input in app level too. I don't expect more from you.. It's my fault because I had to read $PPC FAQ first, as you are too, before implement $PPC support to application and device.

**Comment by peerchemist** [comment] 2018-08-17 14:16
@gre but previous Chrome App works properly, and is working properly for past 18 months or so.

**Comment by gre** [comment] 2018-08-17 15:11
@peerchemist ok thanks for the info. we'll investigate why.

**Comment by es777v** [comment] 2018-08-21 08:10
@gre Hello, I made two Peercoin transactions through the Ledger Live application, the first on August 3rd - 3000 PPC, the second one on August 12th - 3243 PPC . When sending coins, I indicated the recommended commission (high), but transactions are not confirmed to this day. The application gives txid, but it is not in the PPC exploer. Coins did not come out of the purses you indicated, it is seen in the PPC exploer. The application error is an funding gap of the transaction, and these two transactions will not be confirmed forever! 
I repeatedly appealed to support, they respond me very rarely and not on the topic, they offer to wait or skip a screenshot of how to speed up bitcoin, but the topic is not a bitcoin, but unconfirmed  Peercoin transaction. Support request ID  is 192665 
The old Ledger application generates a synchronization error! 
Can you figure out the problem and return my coins to my wallet balance? since the address of the recipient of the first transaction from the third of August is no longer relevant. 
If necessary, I will send all the screenshots of transactions that I have already sent in support of Ledger. 
P.S. I bought a hardware purse Ledger in order to keep my coins safe, and not risk them.

**Comment by jimisan** [comment] 2018-08-22 05:39
@es777v write them at twitter, maybe here https://twitter.com/NatarajDass/status/1030398000181522432 or new;

**Comment by jimisan** [comment] 2018-08-22 05:43
@gre seems your API explorer give you incorrect answers, but .. @peerchemist claims other info .. I interested in investigation results.

**Comment by KhalilBellakrid** [comment] 2018-08-22 14:35
We updated Peercoin fees to 0.01 PPC/kB.
@jimisan could you please send us your transaction's hash ?
Thank you !

**Comment by jimisan** [comment] 2018-08-23 07:51
@KhalilBellakrid. sure it is. Could you give me your public pgp key?

**Comment by KhalilBellakrid** [comment] 2018-08-23 07:54
Would you mind going through our support to send it and post ticket's number? 
Than you !

**Comment by jimisan** [comment] 2018-08-23 08:10
@KhalilBellakrid, here you are: 
#198683

**Comment by KhalilBellakrid** [comment] 2018-08-23 09:01
@jimisan your transaction was dropped, could you please confirm that the issue was solved ? 
 If it persists, you can delete sqlite database located (on MacOS) under `~/Library/Application Support/Ledger Live/sqlite` and relaunch a fresh sync.
@es777v  could you please also send us your transactions hashes through customer support (and post ticket's number here) so we can check that it was successfully dropped ? 
Thank you guys!

**Comment by jimisan** [comment] 2018-08-23 12:33
@KhalilBellakrid now I see a pro hand :). Issue was solved.  in my case : `~/.config/Ledger Live]$ mv sqlite/ sqlite.dd` :+1:

**Comment by jimisan** [comment] 2018-08-23 12:41
@KhalilBellakrid thank you very much.

**Comment by KhalilBellakrid** [comment] 2018-08-23 13:01
@jimisan you're welcome.
@es777v could you please confirm that the issue is also solved from your side so we can close this issue ? 
Thanks !

**Comment by es777v** [comment] 2018-08-23 14:32
@KhalilBellakrid #192665

**Comment by jimisan** [comment] 2018-08-23 15:28
@KhalilBellakrid Could you tell me how you can drop the (probably rejected ) transaction?

**Comment by es777v** [comment] 2018-08-23 15:37
@KhalilBellakrid The problem is not solved. Coins did not return to my balance. Transactions are not confirmed.Txid transactions I sent by mail

**Comment by KhalilBellakrid** [comment] 2018-08-23 15:50
@es777v , I checked we dropped it, if you still have it you should delete PPC accounts on Live and re-import them and if even after that it's still appearing you can delete sqlite database located under `~/Library/Application Support/Ledger Live/sqlite` on MacOS or `C:\Users\<userName>\AppData\Roaming\Ledger Live\sqlite` on Windows and relaunch a fresh sync, then it should be fine !
Please let me know if it's solved, thank you !

**Comment by es777v** [comment] 2018-08-23 16:12
@KhalilBellakrid Thank you!!! Problem solved

**Closed** 2018-08-24 07:50 UTC
Labels: API, needs investigation

**Comment by backpacker69** [comment] 2018-10-24 12:11
btw, peercoin fees are still wrong, not sure why this is closed

**Comment by peerchemist** [comment] 2018-10-24 13:08
Very wrong, I've used some on Ledger yesterday and app calculated fee of 0.0641. Which is simply impossible fee on the Peercoin network.

**Comment by KhalilBellakrid** [comment] 2018-10-24 13:53
@backpacker69 @peerchemist, I just tested Peercoin on Live and we set fees to 1000sat/byte which is 0.01 Peercoin/kB : https://github.com/LedgerHQ/ledger-live-desktop/issues/1377#issuecomment-413667489
