### ISSUE TITLE
Ability to add a comment to any transaction 

### ISSUE THREAD

**Issue by maxocoin** [LedgerHQ/ledger-live-desktop#1837] opened 2019-02-28 00:15 UTC
- [x] I have checked this feature was not yet requested.

On most cryptos you don't have an account name, just an impossible to remember public address to send the funds to.

We need a comment field for keep track why and to whom we sent funds 
Some goes for incoming transaction.

#### Part of the application
In the transactions list, just an edit field for add a comment next to each transaction.

**Comment by juan-cortes** [comment] 2019-02-28 08:03
The idea of a tag system comes around ever so often in the team so it's something we definitely have in mind, as to whether it will be in the form of a comment field for a transaction, a tag, or what, I can't say.

**Comment by 2pac1** [comment] 2019-04-05 08:50
Each transaction needs to be labeled. Not only there is no coin control, but you cant even tag it!? Come on, this is a must

**Comment by bidetaggle** [comment] 2019-04-06 14:20
Hi there! Definitely it would be nice to be able to label any transaction using local storage with a server sync feature using ssh. We would get very close to a double-entry accounting entirely blockchain based, self hosted and private, with the benefit of a hard wallet security.
Further more we can imagine in the future an API for bill automation or whatever the community could create from this point. Ledger could even run their own accounting cloud storage service and gain a new income source.

Personally, I really need this feature to go on to the next step with Ledger Wallet.

Btw, I'm a student looking for an internship worldwide, French native speaker
More about me: https://bidetaggle.com
Feel free to send me a message on github in order to get my contact

**Comment by cthepot-ledger** [comment] 2020-09-14 13:41
Duplicate of #1166

**Closed by cthepot-ledger** 2020-09-14 13:41 UTC
Labels: feature request
