### ISSUE TITLE
Error: Internal process error (3765269347)

### ISSUE THREAD

**Issue by MAX0786** [LedgerHQ/ledger-live-desktop#971] opened 2018-07-09 17:14 UTC
[ledgerlive-export-2018.07.09-20.14.09-c7c5c51e1dd0136251485114e6020ab354789a23.log](https://github.com/LedgerHQ/ledger-live-desktop/files/2177262/ledgerlive-export-2018.07.09-20.14.09-c7c5c51e1dd0136251485114e6020ab354789a23.log)
Error was thrown:

```
Error
    at o (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25413)
    at a (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25600)
    at EventEmitter.l (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:27016)
    at emitTwo (events.js:130:20)
    at EventEmitter.emit (events.js:213:7)
```

**Comment by balthazar** [comment] 2018-07-09 17:38
Duplicate of #933.

**Closed** 2018-07-09 17:40 UTC
