### ISSUE TITLE
No Icon showing in menu bar for Ledger Live on Ubuntu

### ISSUE THREAD

**Issue by chrisengel** [LedgerHQ/ledger-live-desktop#2932] opened 2020-05-22 21:49 UTC
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.3.2
- Platform and version: Ubuntu 20.04 LTS

#### Expected behavior

I expect there to be a Ledger Live icon displaying on the menu when Ledger Live is minimised

#### Actual behavior

There is a blank space in place of an icon

#### Steps to reproduce the behavior

Open Ledger Live and look in the applications menu

![image](https://user-images.githubusercontent.com/12490915/82711868-e6cd8200-9c86-11ea-9426-4b60dd449f9f.png)

**Comment by jesscalvin** [comment] 2020-06-03 03:15
but if i may ask your ledger live works perfectly

**Comment by TrackRunny** [comment] 2020-06-17 00:36
Exact same issue, someone please check this out. I have no icon on the appimage either. The app works fine, just a little annoying. 

Ledger live: 2.5.0
Operating system: Kubuntu 20.04 LTS

**Comment by jesscalvin** [comment] 2020-06-17 00:38
Are you active now .. I could guide you on fixing

**Comment by TrackRunny** [comment] 2020-06-17 00:38
Yes, could you please comment a solution to this issue here?

**Comment by jesscalvin** [comment] 2020-06-17 02:23
Are you using an android or an IOS

**Comment by TrackRunny** [comment] 2020-06-17 17:38
> Are you using an android or an IOS
I'm using Linux, which uses the .appimage version of the program.

**Comment by jesscalvin** [comment] 2020-06-17 17:58
Ok, that’s even much better... do you have a WhatsApp number or Telegram

**Comment by gre** [comment] 2020-06-22 14:10
Please keep the discussion here, we do not offer WhatsApp / Telegram assistance and any help on the current issue is welcomed for contribution. Thanks.

**Comment by cthepot-ledger** [comment] 2020-09-17 13:50
Duplicate of #2300

**Closed by cthepot-ledger** 2020-09-17 13:50 UTC
