### ISSUE TITLE
Ledger Live

### ISSUE THREAD

**Issue by Henrietta1989** [LedgerHQ/ledger-live-desktop#1586] opened 2018-10-16 15:03 UTC
I would be nice if Ledger Live would run in Linux Mint.

Your download page says LL supports only Ubuntu.

**Comment by meriadec** [comment] 2018-10-16 15:09
hey @Henrietta1989, what's the Linux Mint version you are referring?
On our doc we specify we support Ubuntu since version 16.04 (Ubuntu Xenial), which Mint equivalent is 18 (see https://www.linuxmint.com/download_all.php).

**Comment by Henrietta1989** [comment] 2018-10-16 16:20
Mint 19. So it must work then. Thanks!

**Comment by meriadec** [comment] 2018-10-16 16:32
If you don't mind commenting on this issue when confirmed working, so everything is double-checked ^^ then you can close the issue.

**Comment by meriadec** [comment] 2018-10-17 09:45
Let's close for now

**Closed by meriadec** 2018-10-17 09:45 UTC
