### ISSUE TITLE
Borked on 18.04

### ISSUE THREAD

**Issue by jonklinger** [LedgerHQ/ledger-live-desktop#1415] opened 2018-08-13 11:29 UTC
Hi,

Ledger Nano is stuck on this screen in Ubuntu 18.04: 

https://i.imgur.com/HZjXYF0.png

Tried to run as root, tried to change UDEV rules; nothing worked.

In the 1.0.7 It loaded, but could not get to the genuine check; also tried as root. Tried removing .config/local/ledgerlive folder. nothing worked.

Works fine on my 17.10 device.

**Comment by meriadec** [comment] 2018-08-13 11:55
Hey @jonklinger, interesting, if you are stuck here then there is probably a crash on renderer process, but not catched by the error screen. To have more infos, can you, from a terminal:

```
$ DEV_TOOLS=1 ./ledger-live-desktop-1.1.6-linux-x86_64.AppImage
```

this will open dev tools, and you'll be able to screenshot error.
For your second problem (being stuck on onboarding), the problem can comes from multiple sources:

- udev rules (but you already tried) -> maybe try to add your username to each line ([see here](https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Fix-connection-issues))
- issue with usb cable
- having device plugged on a USB hub

**Comment by jonklinger** [comment] 2018-08-13 11:57
Thanks, already tried the USB cable, powered hub, and replacing UDEV.

These are the DEV_Tool errors:

Uncaught Error: /tmp/.org.chromium.Chromium.w5Rxff: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_ledgerVYaOag/app/resources/app.asar/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/tmp/.mount_ledgerVYaOag/app/resources/app.asar/node_modules/usb/usb.js:408:3)

**Comment by meriadec** [comment] 2018-08-13 12:14
Arf.. looks related to load of dynamic library that is failing (we have a few native library, including lib-ledger-core & node-hid (for usb connection)). The kind of problem that are hard to debug & reproduce :(

Is it possible for you to run the app in dev (see README) to see if you have the same problem and if error is more verbose?

On our side we have to set-up an Ubuntu 18.04 to try to reproduce.

**Comment by jonklinger** [comment] 2018-08-13 12:25
Opened up the readme; couldn't find how to run in DEV. What should I change it the ENV?

**Comment by meriadec** [comment] 2018-08-13 12:32
Sry wasn't clear enough! Here are the steps, once you have cloned the repo:
- `yarn` to install deps
- `yarn start` to run the app

**Comment by jonklinger** [comment] 2018-08-13 12:46
well,

Installed NodeJS 8.11.3,
then got this when running Yarn:


yarn install v1.10.0-20180813.1200
error An unexpected error occurred: "Cannot find module \"./rx.lite\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/jonklinger/ledger-live-desktop/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by meriadec** [comment] 2018-08-13 12:51
Strange :D 
looks like a tmp fail during deps install :thinking: can you try `rm -rf node_modules` (from the repo folder) then `yarn` again? If still doesnt' work, don't mind. We will try to reproduce on Ubuntu 18.04 (but I can't give an ETA for this one)

**Comment by jonklinger** [comment] 2018-08-13 12:53
I tried; still keep having the same results.

BTW: Ledger Manager and Ledger Bitcoin wallet work perfectly on this device.

**Comment by jonklinger** [comment] 2018-08-13 13:40
ok;

when I start with a different TMPDIR (TMPDIR=/home/jonklinger/temp ./ledger-live-desktop-1.1.6-linux-x86_64.AppImage it works just fine.

**Comment by meriadec** [comment] 2018-08-13 15:02
Legacy Manager & Wallet aren't using native dependencies, so it's easier to cross-platform (it's using only HTTP for blockchain exploration, and chrome-hid for device communication, while Ledger Live is using libcore & node-hid).

Glad you sorted it out, even I don't really understand what was going on :thinking: 
I'm closing this one for now bcause I don't think there is something we can fix on LL side. Feel free to comment if you find a better workaround.

**Closed by meriadec** 2018-08-13 15:02 UTC
Labels: bug, needs investigation
