### ISSUE TITLE
SOLVE Token cannot get a price

### ISSUE THREAD

**Issue by flamebeard** [LedgerHQ/ledger-live-desktop#2726] opened 2020-03-18 01:37 UTC
- [ x] I have checked this feature was not yet requested.

#### Part of the application does not allow for a price to be retrieved for the SOLVE(Healthcare administration token) token. 

You would be able to get the correct price for your portfolio

**Comment by cthepot-ledger** [comment] 2020-09-16 13:49
Duplicate of #2326

**Closed by cthepot-ledger** 2020-09-16 13:49 UTC
