### ISSUE TITLE
Add more filters to available filters

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#1818] opened 2019-02-20 19:36 UTC
- [x] I have checked this feature was not yet requested.

Currently you can view "week", "month", and "year".
Wouldn't it be nice to also have "day" and maybe 2 or 3 years?
Now you cant see values in the graph that are older than a year.

#### Part of the application

Graphs/Dashboard/Accounts

**Comment by gre** [comment] 2019-05-16 19:55
Definitely

**Comment by ibiscp** [comment] 2020-03-13 23:39
Totally agree, more options like google stocks would be really nice.

<img width="641" alt="Screen Shot 2020-03-14 at 00 37 04" src="https://user-images.githubusercontent.com/19699606/76669502-2d6a7600-658c-11ea-8188-6820bd74266a.png">

**Comment by cthepot-ledger** [comment] 2020-09-14 13:56
Duplicate of #1942

**Closed by cthepot-ledger** 2020-09-14 13:56 UTC
Labels: feature request
