### ISSUE TITLE
How do I close this window without exiting the application or approving on my Ledger?

### ISSUE THREAD

**Issue by Slyke** [LedgerHQ/ledger-live-desktop#3858] opened 2021-05-27 02:29 UTC
Ledger Live Version and Operating System
v2.21.3

tested on Ledger Live version_here
Platform and version: Windows 10
Expected behavior
Should have an X on the top right.

Actual behavior
Can't close modal. Also, on this step on the mobile application one cannot go back unless you exit the app, or approve the transaction.

Steps to reproduce the behavior
Step 3 of receive currency
![image](https://user-images.githubusercontent.com/6442613/119756359-4b9e5800-be58-11eb-87ce-803d3b064ff1.png)

Closing and opening the Ledger Live app does not cause an "invalid state", and neither does force closing this modal when hacking the process with Cheat Engine. #3613

**Comment by valpinkman** [comment] 2021-05-27 10:08
You have to approve the "address" on the device to be able to close this modal.
Doing a receive is not creating any transaction, just displaying your address to be copied somewhere else.
As soon as you validate the address on the device you can close the modal.
You can also ask to display the address without a device (riskier though), and you will be able to close the modal this way without any verification on the device

**Comment by gre** [comment] 2021-05-27 10:11
Yes this behavior happens by design. see also https://github.com/LedgerHQ/ledger-live-desktop/issues/3613#issuecomment-831927169

**Closed by gre** 2021-05-27 10:11 UTC

**Comment by Slyke** [comment] 2021-05-27 18:14
@gre my problem is, why do I have to close the entire process to just get rid of a modal? Why can it be only closed by exiting the process, or accepting it on the hardware device? There is no other way to get your receive address without getting to this step.

This is poor UI design and actually looks like a bug.
