### ISSUE TITLE
Portfolio balance chart longer than 1 Year.

### ISSUE THREAD

**Issue by rheos** [LedgerHQ/ledger-live-desktop#2922] opened 2020-05-15 15:57 UTC
- [x] I have checked this feature was not yet requested.

I've been using my ledger long than a year. Why does the ledger history chart have a limit of 1Y ? Why not 2 or 3 years? Or to whatever date you first started using it?

#### Part of the application

Portfolio balance chart

**Comment by gre** [comment] 2020-05-15 17:10
it's in our pipe yeah. kinda related https://github.com/LedgerHQ/ledger-live-desktop/issues/1488

**Comment by cthepot-ledger** [comment] 2020-09-16 16:42
Duplicate of #1818

**Closed by cthepot-ledger** 2020-09-16 16:42 UTC
